"""Audit event bus for TenantShield.

This module defines the categorical event types, the immutable
:class:`AuditEvent` record, and the :class:`AuditSink` protocol. The
registry, the ``emit()`` dispatcher, and the built-in sinks are added in
subsequent sub-tasks of Sub-phase 1B.

Subscribers ("sinks") consume :class:`AuditEvent` instances. Sinks must
be thread- and async-safe and should not raise. The bus catches sink
exceptions and emits ``SINK_FAILURE`` events to the remaining sinks.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from collections.abc import Mapping

    from tenantshield.context import TenantContext


class AuditEventType(StrEnum):
    """Categorical types of audit events.

    Inherits from ``str`` so events serialize cleanly to JSON without a
    custom encoder.
    """

    CONTEXT_BOUND = "context_bound"
    CONTEXT_RELEASED = "context_released"
    POLICY_ALLOW = "policy_allow"
    POLICY_DENY = "policy_deny"
    ENFORCEMENT_VIOLATION = "enforcement_violation"
    SINK_FAILURE = "sink_failure"


def _empty_payload() -> dict[str, object]:
    """Factory for the default empty payload of AuditEvent."""
    return {}


@dataclass(frozen=True, slots=True, kw_only=True)
class AuditEvent:
    """A single event emitted to the audit bus.

    Attributes:
        event_type: Categorical type of the event.
        tenant_context: The tenant context active when the event occurred,
            or ``None`` if no context was active (e.g. SINK_FAILURE outside
            any scope).
        payload: Arbitrary structured data. Treated as immutable from
            outside the package; mutating it does not break TenantShield
            invariants but is bad style.
        timestamp: UTC timestamp at construction time. Generated by
            ``datetime.now(timezone.utc)`` per instance via
            ``default_factory``.
    """

    event_type: AuditEventType
    tenant_context: TenantContext | None
    payload: Mapping[str, object] = field(default_factory=_empty_payload)
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))


@runtime_checkable
class AuditSink(Protocol):
    """Contract for audit event consumers.

    Implementations must be thread- and async-safe. Implementations should
    not raise exceptions; if they do, the bus catches them and emits a
    ``SINK_FAILURE`` event to the remaining sinks. Repeated failures from
    the same sink do not cause infinite recursion: the failure event is
    dispatched to sinks OTHER than the one that failed.
    """

    def emit(self, event: AuditEvent) -> None: ...  # pragma: no cover


__all__ = [
    "AuditEvent",
    "AuditEventType",
    "AuditSink",
]
