"""Audit event bus for TenantShield.

This module defines the categorical event types, the immutable
:class:`AuditEvent` record, and the :class:`AuditSink` protocol. The
registry, the ``emit()`` dispatcher, and the built-in sinks are added in
subsequent sub-tasks of Sub-phase 1B.

Subscribers ("sinks") consume :class:`AuditEvent` instances. Sinks must
be thread- and async-safe and should not raise. The bus catches sink
exceptions and emits ``SINK_FAILURE`` events to the remaining sinks.
"""

from __future__ import annotations

import contextlib
import threading
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import TYPE_CHECKING, Protocol, runtime_checkable

import structlog

if TYPE_CHECKING:
    from collections.abc import Mapping

    from structlog.stdlib import BoundLogger

    from tenantshield.context import TenantContext


class AuditEventType(StrEnum):
    """Categorical types of audit events.

    Inherits from ``str`` so events serialize cleanly to JSON without a
    custom encoder.
    """

    CONTEXT_BOUND = "context_bound"
    CONTEXT_RELEASED = "context_released"
    POLICY_ALLOW = "policy_allow"
    POLICY_DENY = "policy_deny"
    ENFORCEMENT_VIOLATION = "enforcement_violation"
    SINK_FAILURE = "sink_failure"


def _empty_payload() -> dict[str, object]:
    """Factory for the default empty payload of AuditEvent."""
    return {}


@dataclass(frozen=True, slots=True, kw_only=True)
class AuditEvent:
    """A single event emitted to the audit bus.

    Attributes:
        event_type: Categorical type of the event.
        tenant_context: The tenant context active when the event occurred,
            or ``None`` if no context was active (e.g. SINK_FAILURE outside
            any scope).
        payload: Arbitrary structured data. Treated as immutable from
            outside the package; mutating it does not break TenantShield
            invariants but is bad style.
        timestamp: UTC timestamp at construction time. Generated by
            ``datetime.now(timezone.utc)`` per instance via
            ``default_factory``.
    """

    event_type: AuditEventType
    tenant_context: TenantContext | None
    payload: Mapping[str, object] = field(default_factory=_empty_payload)
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))


@runtime_checkable
class AuditSink(Protocol):
    """Contract for audit event consumers.

    Implementations must be thread- and async-safe. Implementations should
    not raise exceptions; if they do, the bus catches them and emits a
    ``SINK_FAILURE`` event to the remaining sinks. Repeated failures from
    the same sink do not cause infinite recursion: the failure event is
    dispatched to sinks OTHER than the one that failed.
    """

    def emit(self, event: AuditEvent) -> None: ...  # pragma: no cover


class NullSink:
    """A sink that discards all events. Useful for tests and as default."""

    def emit(self, event: AuditEvent) -> None:
        pass


class InMemorySink:
    """A sink that accumulates events in memory.

    Not thread-safe by design for performance — intended for tests where
    the test controls concurrency. If you need thread-safety in production
    code, build a different sink.

    Attributes:
        events: List of emitted events, in order.
    """

    def __init__(self) -> None:
        self.events: list[AuditEvent] = []

    def emit(self, event: AuditEvent) -> None:
        self.events.append(event)

    def clear(self) -> None:
        """Remove all accumulated events."""
        self.events.clear()


class StructLogSink:
    """An audit sink that forwards events to a structlog ``BoundLogger``.

    The sink does NOT configure structlog globally. The caller is responsible
    for the structlog processor chain. If no logger is provided, the sink
    uses ``structlog.get_logger("tenantshield.audit")`` which inherits the
    caller's global structlog configuration.

    Args:
        logger: An optional pre-configured structlog logger. If ``None``, a
            default logger bound to ``"tenantshield.audit"`` is used.

    Example:
        >>> import structlog
        >>> from tenantshield.audit import StructLogSink, register_sink
        >>> logger = structlog.get_logger("my_app").bind(component="tenancy")
        >>> register_sink(StructLogSink(logger=logger))
    """

    def __init__(self, logger: BoundLogger | None = None) -> None:
        self._logger = logger or structlog.get_logger("tenantshield.audit")

    def emit(self, event: AuditEvent) -> None:
        self._logger.info(
            event.event_type.value,
            timestamp=event.timestamp.isoformat(),
            tenant_id=event.tenant_context.tenant_id if event.tenant_context else None,
            payload=dict(event.payload),
        )


_SINKS_REGISTRY: list[AuditSink] = []
_REGISTRY_LOCK = threading.RLock()


def register_sink(sink: AuditSink) -> None:
    """Register a sink to receive audit events.

    Idempotent: registering the same sink twice (verified by identity) has
    no effect on the second call.
    """
    with _REGISTRY_LOCK:
        if sink not in _SINKS_REGISTRY:
            _SINKS_REGISTRY.append(sink)


def unregister_sink(sink: AuditSink) -> None:
    """Unregister a sink. If not registered, this is a no-op."""
    with _REGISTRY_LOCK, contextlib.suppress(ValueError):
        _SINKS_REGISTRY.remove(sink)


def emit(event: AuditEvent) -> None:
    """Dispatch an event to all registered sinks.

    Sinks that raise exceptions do not interrupt other sinks. For each
    failing sink, a ``SINK_FAILURE`` event is emitted to all OTHER
    registered sinks (preventing infinite recursion). A second-level
    failure (the ``SINK_FAILURE`` itself failing) is silently suppressed.
    """
    with _REGISTRY_LOCK:
        snapshot = list(_SINKS_REGISTRY)

    for sink in snapshot:
        try:
            sink.emit(event)
        except Exception as exc:
            _emit_sink_failure(
                failing_sink=sink,
                original_event=event,
                error=exc,
                all_sinks=snapshot,
            )


def _emit_sink_failure(
    *,
    failing_sink: AuditSink,
    original_event: AuditEvent,
    error: BaseException,
    all_sinks: list[AuditSink],
) -> None:
    """Emit a SINK_FAILURE event to all sinks except the one that failed."""
    failure_event = AuditEvent(
        event_type=AuditEventType.SINK_FAILURE,
        tenant_context=original_event.tenant_context,
        payload={
            "failing_sink_type": type(failing_sink).__name__,
            "original_event_type": original_event.event_type.value,
            "error_type": type(error).__name__,
            "error_message": str(error),
        },
    )
    for sink in all_sinks:
        if sink is failing_sink:
            continue
        with contextlib.suppress(Exception):
            sink.emit(failure_event)


__all__ = [
    "AuditEvent",
    "AuditEventType",
    "AuditSink",
    "InMemorySink",
    "NullSink",
    "StructLogSink",
    "emit",
    "register_sink",
    "unregister_sink",
]
